import os
import shutil as s
print(os.getcwd())
os.chdir('../')
print(os.getcwd())
print(os.listdir())
os.chdir('directory')
print(os.getcwd())
#os.mkdir('new folder1')
print(os.listdir())
#os.rmdir('new folder1')
print(os.listdir())
#os.rename('new folder','my folder')
print(os.listdir())
#os.chdir('my folder')
print(os.getcwd())
#os.mkdir('a')
#os.mkdir('b')
print(os.listdir())
os.chdir('../')
print(os.getcwd())
#s.rmtree('my folder')
print(os.getcwd())
print(os.listdir())
